FROM openjdk:17-jdk

VOLUME /tmp
WORKDIR /app

COPY target/*.jar /app/app.jar

# Definindo ARGs para permitir a customização durante o build
ARG CONFIG_SERVER_HOST
ARG EUREKA_SERVER_REGISTER_WITH_EUREKA=false
ARG EUREKA_SERVER_FETCH_REGISTRY=false
ARG EUREKA_SERVER_WAIT_TIME=0
ARG EUREKA_SERVER_ENABLE_SELF_PRESERVATION=false
ARG EUREKA_SERVER_EVICTION_INTERVAL=5000
ARG PORT=8761
ARG JAVA_OPTS="-Xmx256m -XX:+UseG1GC"

# Passando os ARGs para as variáveis de ambiente
ENV CONFIG_SERVER_HOST=${CONFIG_SERVER_HOST}
ENV EUREKA_SERVER_REGISTER_WITH_EUREKA=${EUREKA_SERVER_REGISTER_WITH_EUREKA}
ENV EUREKA_SERVER_FETCH_REGISTRY=${EUREKA_SERVER_FETCH_REGISTRY}
ENV EUREKA_SERVER_WAIT_TIME=${EUREKA_SERVER_WAIT_TIME}
ENV EUREKA_SERVER_ENABLE_SELF_PRESERVATION=${EUREKA_SERVER_ENABLE_SELF_PRESERVATION}
ENV EUREKA_SERVER_EVICTION_INTERVAL=${EUREKA_SERVER_EVICTION_INTERVAL}
ENV PORT=${PORT}
ENV JAVA_OPTS=${JAVA_OPTS}

# Configurando o entrypoint
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
