services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG_SERVER_HOST: "${CONFIG_SERVER_HOST:-}"
      EUREKA_SERVER_REGISTER_WITH_EUREKA: "${EUREKA_SERVER_REGISTER_WITH_EUREKA:-false}"
      EUREKA_SERVER_FETCH_REGISTRY: "${EUREKA_SERVER_FETCH_REGISTRY:-false}"
      EUREKA_SERVER_WAIT_TIME: "${EUREKA_SERVER_WAIT_TIME:-0}"
      EUREKA_SERVER_ENABLE_SELF_PRESERVATION: "${EUREKA_SERVER_ENABLE_SELF_PRESERVATION:-false}"
      EUREKA_SERVER_EVICTION_INTERVAL: "${EUREKA_SERVER_EVICTION_INTERVAL:-5000}"
    ports:
      - "8761:8761"