FROM openjdk:17-jdk

VOLUME /tmp
WORKDIR /app

COPY target/*.jar /app/app.jar

ENV CONFIG_SERVER_HOST=
ENV EUREKA_SERVER_REGISTER_WITH_EUREKA=false
ENV EUREKA_SERVER_FETCH_REGISTRY=false
ENV EUREKA_SERVER_WAIT_TIME=0
ENV EUREKA_SERVER_ENABLE_SELF_PRESERVATION=false
ENV EUREKA_SERVER_EVICTION_INTERVAL=5000

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
